/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_monk_jni_JniFragment */

#ifndef _Included_com_monk_jni_JniFragment
#define _Included_com_monk_jni_JniFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_monk_jni_JniFragment
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_monk_jni_JniFragment_sayHello
  (JNIEnv *, jobject,jstring);

#ifdef __cplusplus
}
#endif
#endif
